% saveLidarSubMaps('/home/yinhuan/Data/radar_loc/02.07/seq01_laser_pc/', ...
%     '/home/yinhuan/Data/radar_lidar_pr/Oxford/seq01/lidar_pt/', pose_xy_01, ...
%     64, 64, 0.2);


% saveLidarSubMaps('/home/yinhuan/Data/183/mulran/Kaist01/lidar_pt/', ...
%     '/home/yinhuan/Data/radar_lidar_pr/Mulran/Kaist01/lidar_pt/', pose_kaist_01, ...
%     64, 64, 0.2);


% longer range
% saveLidarSubMaps('/home/yinhuan/Data/183/mulran/Kaist01/lidar_pt/', ...
%     '/home/yinhuan/Data/radar_lidar_pr/Mulran/Kaist01_80/lidar_pt/', pose_kaist_01, ...
%     80, 80, 0.2);

% saveLidarSubMaps('/home/yinhuan/Data/183/mulran/Kaist02/lidar_pt/', ...
%     '/home/yinhuan/Data/radar_lidar_pr/Mulran/Kaist02_80/lidar_pt/', pose_kaist_02, ...
%     80, 80, 0.2);




% % 
% saveLidarSubMaps('/home/yinhuan/Data/183/mulran/DCC01/lidar_pt/', ...
%     '/home/yinhuan/Data/radar_lidar_pr/Mulran/DCC01_80/lidar_pt/', pose_dcc_01, ...
%     80, 80, 0.2);
% 
% saveLidarSubMaps('/home/yinhuan/Data/183/mulran/DCC02/lidar_pt/', ...
%     '/home/yinhuan/Data/radar_lidar_pr/Mulran/DCC02_80/lidar_pt/', pose_dcc_02, ...
%     80, 80, 0.2);




%% 01.08


% saveLidarSubMaps('/home/yinhuan/Data/183/mulran/Kaist01/lidar_pt/', ...
%     '/home/yinhuan/Data/radar_lidar_pr/Mulran/Kaist01_80/lidar_pt/', pose_kaist_01, ...
%     80, 80, pi/2, 0.2);
% 
% saveLidarSubMaps('/home/yinhuan/Data/183/mulran/Kaist02/lidar_pt/', ...
%     '/home/yinhuan/Data/radar_lidar_pr/Mulran/Kaist02_80/lidar_pt/', pose_kaist_02, ...
%     80, 80, pi/2, 0.2);




% saveLidarSubMaps('/home/yinhuan/Data/183/mulran/DCC01/lidar_pt/', ...
%     '/home/yinhuan/Data/radar_lidar_pr/Mulran/DCC01_80/lidar_pt/', pose_dcc_01, ...
%     80, 80, pi/2, 0.2);


%% 01.27

% saveLidarSubMaps('/home/yinhuan/Data/183/mulran/Riverside01/lidar_pt/', ...
%     '/home/yinhuan/Data/radar_lidar_pr/Mulran/Riverside01_80/lidar_pt/', pose_riverside_01, ...
%     80, 80, pi/2, 0.2);
% 
% saveLidarSubMaps('/home/yinhuan/Data/183/mulran/Riverside02/lidar_pt/', ...
%     '/home/yinhuan/Data/radar_lidar_pr/Mulran/Riverside02_80/lidar_pt/', pose_riverside_02, ...
%     80, 80, pi/2, 0.2);




saveLidarSubMaps('/home/yinhuan/Data/183/mulran/Riverside01/lidar_pt_0128/', ...
    '/home/yinhuan/Data/radar_lidar_pr/Mulran/Riverside01_80/lidar_pt_0128/', pose_riverside_01, ...
    80, 80, pi/2, 0.2);

saveLidarSubMaps('/home/yinhuan/Data/183/mulran/Riverside02/lidar_pt_0128/', ...
    '/home/yinhuan/Data/radar_lidar_pr/Mulran/Riverside02_80/lidar_pt_0128/', pose_riverside_02, ...
    80, 80, pi/2, 0.2);





