% saveLasers('/home/yinhuan/Data/183/mulran/Kaist01/lidar_pt/', ...
%         '/home/yinhuan/Data/bypy/Kaist01/Ouster/', ...
%         '/home/yinhuan/Data/bypy/Kaist01/ouster_front_stamp.csv',...
%         '/home/yinhuan/Data/bypy/Kaist01/navtech_top_stamp.csv', ...
%         base2lidar, base2radar);


% saveLasers('/home/yinhuan/Data/183/mulran/DCC01/lidar_pt/', ...
%         '/home/yinhuan/Data/bypy/DCC01/Ouster/', ...
%         '/home/yinhuan/Data/bypy/DCC01/ouster_front_stamp.csv',...
%         '/home/yinhuan/Data/bypy/DCC01/navtech_top_stamp.csv', ...
%         base2lidar, base2radar);


% saveLasers('/home/yinhuan/Data/183/mulran/Riverside02/lidar_pt/', ...
%         '/home/yinhuan/Data/bypy/Riverside02/Ouster/', ...
%         '/home/yinhuan/Data/bypy/Riverside02/ouster_front_stamp.csv',...
%         '/home/yinhuan/Data/bypy/Riverside02/navtech_top_stamp.csv', ...
%         base2lidar, base2radar);
    
% saveLasers('/home/yinhuan/Data/183/mulran/Sejong01/lidar_pt/', ...
%         '/home/yinhuan/Data/bypy/Sejong01/Ouster/', ...
%         '/home/yinhuan/Data/bypy/Sejong01/ouster_front_stamp.csv',...
%         '/home/yinhuan/Data/bypy/Sejong01/navtech_top_stamp.csv', ...
%         base2lidar, base2radar);


%% KAIST 01 can not cover the area, use 02 

% saveLasers('/home/yinhuan/Data/183/mulran/Kaist02/lidar_pt/', ...
%         '/home/yinhuan/Data/bypy/Kaist02/Ouster/', ...
%         '/home/yinhuan/Data/bypy/Kaist02/ouster_front_stamp.csv',...
%         '/home/yinhuan/Data/bypy/Kaist02/navtech_top_stamp.csv', ...
%         base2lidar, base2radar);

%% RiverSide try

saveLasers('/home/yinhuan/Data/183/mulran/Riverside02/lidar_pt/', ...
        '/home/yinhuan/Data/bypy/Riverside02/Ouster/', ...
        '/home/yinhuan/Data/bypy/Riverside02/ouster_front_stamp.csv',...
        '/home/yinhuan/Data/bypy/Riverside02/navtech_top_stamp.csv', ...
        base2lidar, base2radar);
