
saveLidarSubMaps('/home/yinhuan/Data/183/mulran/Riverside01/lidar_pt/', ...
    '/home/yinhuan/Data/radar_lidar_pr/Mulran/Riverside01_80/lidar_pt/', pose_riverside_01, ...
    80, 80, pi/2, 0.2);

saveLidarSubMaps('/home/yinhuan/Data/183/mulran/Riverside02/lidar_pt/', ...
    '/home/yinhuan/Data/radar_lidar_pr/Mulran/Riverside02_80/lidar_pt/', pose_riverside_02, ...
    80, 80, pi/2, 0.2);



