% training in mulran Dcc-01
% 
% saveLasers('/home/yinhuan/Data/radar_lidar_pr/Mulran/DCC02/lidar_pt/', ...
%         '/home/yinhuan/Data/MulRan/DCC02/Ouster/', ...
%         '/home/yinhuan/Data/MulRan/DCC02/ouster_front_stamp.csv',...
%         '/home/yinhuan/Data/MulRan/DCC02/navtech_top_stamp.csv');
%     
    
% saveLasers('/home/yinhuan/Data/radar_lidar_pr/Mulran/Kaist01/lidar_pt/', ...
%         '/home/yinhuan/Data/MulRan/Kaist01/Ouster/', ...
%         '/home/yinhuan/Data/MulRan/Kaist01/ouster_front_stamp.csv',...
%         '/home/yinhuan/Data/MulRan/Kaist01/navtech_top_stamp.csv');
